### ISSUE TITLE
Minos out of order in pattern?

### ISSUE THREAD

**Issue by moozilla** [knewjade/solution-finder#1]
When I search with a pattern such as `[IJLOS]p5,S` I receive results for patterns such as `SISLJO`, with the S mino in the middle. Since I specify S mino to appear at the end of the sequence, shouldn't this result be impossible? (I expect results only from sequences such as `xxxxxS`.)

Example:
`sfinder path -t v115@zgyhGexhHexhGeAtxhC8BeA8BtyhE8AtA8JeAgWBAV?AAAAvhAAAPBAUAAAA -P 2 -p [IJLOS]p5,S --split yes`

Impossible result:
http://fumen.zui.jp/?v115@9gC8GeB8HeB8GeF8BeC8JeXIYZAFLDmClcJSAVDEHB?EooRBToAVBJNUPCvAAAAvhEJnB/rBCoBGmBTqB

---

すみません、私は日本語をあまり話しません。 私は私の質問でGoogle翻訳を使用しました：

`[IJLOS] p5,S` のようなパターンで検索すると、中央にS minoを持つ`SISLJO`などのパターンの結果が表示されます。 シーケンスの最後にS minoを指定するので、これは不可能ではないでしょうか？ （私は`xxxxxS`のようなシーケンスからの結果しか期待していません）

**Comment by knewjade** [comment]
Thank you for the report. I fixed this issue in [v0.506](https://github.com/knewjade/solution-finder/releases/tag/v0.506).

v0.505
[http://fumen.zui.jp/?v115@9gC8GeB8HeB8GeF8BeC8JeXIYZAFLDmClcJSAVDEHB?EooRBToAVBJNUPCvAAAAvhEJnB/rBCoBGmBTqB](http://fumen.zui.jp/?v115@9gC8GeB8HeB8GeF8BeC8JeXIYZAFLDmClcJSAVDEHB?EooRBToAVBJNUPCvAAAAvhEJnB/rBCoBGmBTqB)
`S-Spawn I-Left S-Left L-Reverse J-Reverse O-Spawn [SOSILJ, SISJLO, ISLOSJ, IOSSLJ, SSIJLO, SOILSJ, SLOISJ, SISLJO, SSILJO, ISOSJL, ISSJLO, IOSLSJ, OSSJIL, ISSLJO, OISSJL, OSISJL, SOSJIL, SLSJIO, SIJSLO, OISJSL, OSLSJI, OSIJSL, SOISJL, SSJLIO, SLISJO, OSSIJL, SOLSJI, OSLSIJ, SSJILO, ISJSLO, SOSIJL, SLSIJO, IOSSJL, OSJSIL, SOLSIJ, SIOSLJ, SLIOSJ, IOSJSL, SSLJIO, SJISLO, OSSJLI, OSLISJ, ISOSLJ, SILSJO, SJSLIO, SIOLSJ, SLOSJI, OSSLJI, OSJISL, SOSJLI, SOLISJ, SJSILO, OISSLJ, OSISLJ, SSLIJO, ISLSJO, SOSLJI, SLOSIJ, ISOLSJ, OSSLIJ, SILOSJ, SOISLJ, OSSILJ, SOSLIJ, OISLSJ, OSILSJ, OSJSLI, SIOSJL]`

v0.506
[http://fumen.zui.jp/?v115@9gC8GeB8HeB8GeF8BeC8JeXIYZAFLDmClcJSAVDEHB?EooRBToAVBJHstCqAAAAvhEJnBTlBCjB/rBGrB](http://fumen.zui.jp/?v115@9gC8GeB8HeB8GeF8BeC8JeXIYZAFLDmClcJSAVDEHB?EooRBToAVBJHstCqAAAAvhEJnBTlBCjB/rBGrB)
`S-Spawn I-Left O-Spawn L-Reverse S-Left J-Reverse [ISLOSJ, SOILSJ, SLOISJ, IOSLSJ, OISJSL, OSIJSL, SLIOSJ, IOSJSL, OSLISJ, SIOLSJ, OSJISL, SOLISJ, ISOLSJ, SILOSJ, OISLSJ, OSILSJ]`

---

> Since I specify S mino to appear at the end of the sequence, shouldn't this result be impossible? (I expect results only from sequences such as xxxxxS.)

No, this result is possible because can use hold. When use hold, expected sequences is `xxxxxS` or `xxxxSx`. If you need `xxxxxS` only, please specify option to avoid hold. (`--hold avoid`)
