### ISSUE TITLE
Prepare documentation for translation

### ISSUE THREAD

**Issue by Darylgolden** [knewjade/solution-finder#7]
First of all, thank you for this wonderful program!

I noticed that the documentation is only available in Japanese. Since machine translation between Japanese and English isn't very good, especially when there is so much subject specific terminology that a machine couldn't possibly know. I don't speak Japanese, but I have helped set up the translation infrastructure for another project that uses Sphinx ([Manim](https://github.com/ManimCommunity/manim)) and can therefore help with setting it up here if there is interest in doing so. This will allow anyone interested in translating to do so easily and have their contributions viewable directly from the documentation website through a version switcher.

**Comment by knewjade** [comment]
Thank you for your advise.

I too am convinced that translation of documentation is a big issue. This project was driven by personal intellectual curiosity and I did not expect it to be used to this extent. I have no confidence in my English, so I have not been able to create it until now.

However, I think this issue is a good opportunity. As a first start, we would like to consider infrastructure for multilingual. I am not sure how the actual content will be translated, but I am hopeful that there will be a good movement.

Probably I can set up an infrastructure for multilingual. And when it is completed, I will close this Issue.
(I was versioning documents but removed it. the use case of this software is to obtain theoretical values, and if past versions are used, the values may change due to bugs. Therefore, we do not recommend using past versions, although they are kept as a trail.)

**Comment by Darylgolden** [comment]
Thanks for your reply!

Manim uses Sphinx, ReadTheDocs and Crowdin for its documentation. I noticed that you are using GitHub pages. While it is possible to set up internationalization with that, it's a lot simpler just to use RTD. If you are happy with also using this infrastructure for this project, I can help set it up.

**Comment by knewjade** [comment]
Documentation has been moved to https://solution-finder.readthedocs.io. Also, the top page has been translated. Language switching is working well, so I will close this Issue. Thanks for your advice!
